home:
   path: /
   controller: App\Controller\HomeController::index

product:
   path: /products
   controller: App\Controller\ProductController::index

product_id:
   path: /products/{id}
   controller: App\Controller\ProductController::view
